### ISSUE TITLE
在安装好MongoDB集群之后，扩展了一个节点，服务异常！

### ISSUE THREAD

**Issue by silence-liu** [cas-bigdatalab/ambari-mongodb-cluster#1]
你好，我使用了该Ambari-mongodb-cluster插件之后，成功的安装了Mongodb集群到Ambari上，但是我稍后再集群中增加了一个节点，然后数据分片的配置自动发生了变化，但是除了新增的shard，之前的每个shard对应的数据并没有迁移到对应的节点上。这导致MongoDB服务不可用了。

没添加节点之前的配置：
![image](https://user-images.githubusercontent.com/20079928/32363037-2f9ff714-c0a8-11e7-8f19-9b079ce09ff7.png)

shard2
![image](https://user-images.githubusercontent.com/20079928/32363171-e482062c-c0a8-11e7-8a2f-1c191bf9e984.png)

shard1
![image](https://user-images.githubusercontent.com/20079928/32363108-92ea5f58-c0a8-11e7-9c75-54ca11f19d22.png)

shard0
![image](https://user-images.githubusercontent.com/20079928/32363328-c870675c-c0a9-11e7-8a65-1968a04aa7c8.png)

然后我在Ambari管理界面添加了 Nodegroup配置
![image](https://user-images.githubusercontent.com/20079928/32363390-1aec730e-c0aa-11e7-8d80-c2a6da4e9607.png)

保存配置：
![image](https://user-images.githubusercontent.com/20079928/32363423-43025e80-c0aa-11e7-8d24-b2c0959bee17.png)

在新增的服务器上添加MONGODB服务
![image](https://user-images.githubusercontent.com/20079928/32363463-7687f3be-c0aa-11e7-9207-c68e5c8cf7b8.png)

安装服务：
![qq 20171103152438](https://user-images.githubusercontent.com/20079928/32363754-c8e5432c-c0ab-11e7-80ab-5a2194e48553.jpg)

重启所有Mongo服务：
![image](https://user-images.githubusercontent.com/20079928/32363780-f4196212-c0ab-11e7-918c-9be482295a90.png)

查看集群状态： 配置已经发生变化，除了shard3，其他的shard有原来的集群分配到了新的集群，但是只有配置发生了变化，数据全都没有进行移动。
![image](https://user-images.githubusercontent.com/20079928/32364019-6fdf893e-c0ad-11e7-8d88-b258449f133b.png)
![default](https://user-images.githubusercontent.com/20079928/32364169-4e359502-c0ae-11e7-9d57-7729526db536.png)

查看分片状态，除了新增的shard3分片，其他分片都不再可用。
![qq 20171103154949](https://user-images.githubusercontent.com/20079928/32364230-a6c4c5f8-c0ae-11e7-9221-586aa42c9be7.jpg)

请给我一些建议。是否因为哪里配置的不对导致此问题！
假设我的集群中存在大量数据的情况下，新增借点导致集群不可用这几乎是致命的。

**Comment by csxuyang** [comment]
我按照你的操作走了一遍，展示跟你的不太一样，但是也会有一些问题，重新划分片的时候出现，这个问题还得考虑一下

**Comment by csxuyang** [comment]
已提交修改
